# Profil dev : rechargement automatique (DevTools)
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Thymeleaf : pas de cache pour voir les changements de templates tout de suite
spring.thymeleaf.cache=false

# Logs un peu plus verbeux en dev (optionnel)
logging.level.org.springframework.web=INFO
